const ACTION_TYPE = {
    CURRENT_CITY: "CURRENT_CITY",
    FORECAST_CITY_BY_DAYS: "FORECAST_CITY_BY_DAYS",
    SEARCHED_CITIES: "SEARCHED_CITIES",
    CLEAR_SEARCHED_CITIES:"CLEAR_SEARCHED_CITIES"
}
export default ACTION_TYPE;